### ISSUE TITLE
Problem with the software on ESP-12F

### ISSUE THREAD

**Issue by hogin86** [andrei7c4/weatherdisplay#3]
Hello,

I have compiled the project according to your instructions on Linux.
Then I have these imported and the settings made for WLAN etc.

But unfortunately the whole thing is always and I can enter nothing more and nothing happens.

lll▒▒r▒l▒▒mode : sta(5c:cf:7f:f8:6d:5e)
add if0
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 1
cnt
connected with homebox, channel 6
ip:192.168.0.121,mask:255.255.255.0,gw:192.168.0.100
state: 5 -> 0 (0)
rm 0
del if0
usl

This issue now comes at the start and then nothing happens.

Can you help me, what could I have done wrong?

Best Regards 

Martin

**Comment by andrei7c4** [comment]
Hi,
Have you entered other settings like OWM AppId and the city? The device will go into sleep mode after 20 seconds so you need to enter those straight after the reset. Alternatively you can modify default values in config.h, which might be easier if you are able to compile own binaries.

Andrei

**Comment by hogin86** [comment]
Hi,

I have now made my settings in the config.h.
But still no display and the terminal hangs already more than 20 seconds.

lll`▒▒r▒l▒▒▒▒▒▒▒retain found
valid config found
mode : sta(5c:cf:7f:f8:6d:5e)
add if0
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 4
cnt

connected with homebox, channel 6
ip:192.168.0.121,mask:255.255.255.0,gw:192.168.0.100
state: 5 -> 0 (0)
rm 0
del if0
usl

Martin

**Comment by andrei7c4** [comment]
Try to enable debug by commenting out `#define NDEBUG ` line in debug.h and setting `config->debugEn` to TRUE in config.c.

**Comment by hogin86** [comment]
Now I get this error message when compiling.

/home/hogin/ESP/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: build/app.out section `.text' will not fit in region `iram1_0_seg'
collect2: error: ld returned 1 exit status
Makefile:188: recipe for target 'build/app.out' failed
make: *** [build/app.out] Error 1

**Comment by andrei7c4** [comment]
You can flash my pre-built binaries from app/firmware/ and enable debug through the serial port by giving command `debug:1`.

**Comment by hogin86** [comment]
this is coming now with your bin's 

but
parseWeather failed

and no Screen 

▒l`▒▒r▒l▒|W▒▒▒▒retain found
valid config found
Built on Oct  3 2017 20:13:20
SDK version 1.5.4(baaeaebb)
attempts 1, fails 1, retry 1
appState 1
mode : sta(5c:cf:7f:f8:6d:5e)
add if0
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 1
cnt

connected with homebox, channel 6
ip:192.168.0.121,mask:255.255.255.0,gw:192.168.0.100
appState 2
getHostByNameCb ip: 95.85.63.65
appState 3
appState 4
onTcpDataSent
onTcpDataReceived 425
parseHttpReply 425
parseWeather failed
OWM 404
appState 10
sleepTime 1800000000
state: 5 -> 0 (0)
rm 0
del if0
usl

**Comment by andrei7c4** [comment]
Can you try with some other city? Is your city found here http://openweathermap.org/find ?

**Comment by hogin86** [comment]
http://openweathermap.org/city/2922085 

I then again deleted everything and a second trial started, unfortunately, is now following boot loop

lll`▒▒r▒l▒▒▒▒▒▒▒retain found
valid config found
Fatal exception 3(LoadStoreErrorCause):
epc1=0x4000deed, epc2=0x00000000, epc3=0x00000000, excvaddr=0x40000050, depc=0x00000000

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 32768, room 16
tail 0
chksum 0xa7
load 0x3ffe8000, len 4244, room 8
tail 12
chksum 0xaa
ho 0 tail 12 room 4
load 0x3ffe90a0, len 1980, room 12
tail 0
chksum 0x43
csum 0x43

**Comment by andrei7c4** [comment]
I am sorry, but I run out of ideas. I tested your city on my device and it worked fine.

**Comment by hogin86** [comment]
There is a difference to the ESP-E and ESP-F ?

**Comment by hogin86** [comment]
https://github.com/pfalcon/esp-open-sdk

I have this git loaded and only use "make" is that correct?

**Comment by andrei7c4** [comment]
I am not sure about all the differences between 12E and 12F, but I think the F model should work as well.

Yes, `make` is enough to build esp-open-sdk.

**Comment by andrei7c4** [comment]
You can try the following:

Clear ESP8266 flash completely, follow the instructions from here: http://www.pratikpanda.com/completely-format-erase-esp8266-flash-memory/

Then flash my binaries. Use this terminal to configure settings: https://sites.google.com/site/terminalbpp/

Configure setting in the following order:
`debug:1`
`appid:owmappid`
`city:London`
`ssid:yourwifissid`
`pass:yourwifipass`

If that configuration works, then change to your city.

**Comment by hogin86** [comment]
Hi Andrei,

I had at "city:" the website ID and not the city name. This then led to a crash.

**But now it works :+1:** 

Martin

**Comment by andrei7c4** [comment]
Hi Martin,
I am glad you made it work.
