### ISSUE TITLE
ESP remains in boot mode // rst cause:2, boot mode:(3,6)

### ISSUE THREAD

**Issue by jqmcginnis** [andrei7c4/weatherdisplay#4]
I am trying to build weatherdisplay using the esp-open-sdk toolchain as described in your readme.
The make and flash process are carried out successfully, however the esp won't leave the boot-mode at reset with the following error message (displayed when connecting to the serial port):

ets Jan 8 2013, rst cause:2, boot mode: (3,6)
[...]
valid config found
Fatal exception 3(LoadStoreErrorCause):
epc1=0x4000deed, epc2=0x00000000, epc3= 0x00000000, excvaddr=0x40000014

I am using the NodeMCUV3. I have tried with external powering and multiple nodemcu boards, however the esp won't leave boot mode. Any ideas on what I am doing wrong?

**Comment by andrei7c4** [comment]
Hi,
If you have modified the default strings in config.h, make sure you do not exceed allocated buffers in Config struct.

**Comment by samyness** [comment]
Same problem here! 

valid retain found
valid config found
Built on Apr 13 2020 17:12:07
SDK version 2.2.0-dev(9422289)
attempts 7, fails 6, retry 0
appState 1
mode : sta(ec:fa:bc:5f:ab:8d)
add if0
timeoutTmrCb, appState 1
appState 10

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 32124, room 16
tail 12
chksum 0xcc
ho 0 tail 12 room 4
load 0x3ffe8000, len 2688, room 12
tail 4
chksum 0xd0
load 0x3ffe8a80, len 3328, room 4
tail 12
chksum 0x78
csum 0x78
