### ISSUE TITLE
The chosen display is now obsolete, any replacement ideas?

### ISSUE THREAD

**Issue by njbuch** [andrei7c4/weatherdisplay#5]
Project looks awesome, but the display used is not available anymore. Any ideas?

**Comment by andrei7c4** [comment]
Yes, I am planning to port software to use this display: https://www.waveshare.com/product/modules/oleds-lcds/e-paper/7.5inch-e-paper.htm?___SID=U

**Comment by njbuch** [comment]
Sounds awesome, will keep watching! :)

**Comment by d-gattermann** [comment]
Any plans for adding ESP32 support?

**Comment by FrAllard** [comment]
It would be interesting to get the one with a second color, yellow would be perfect I think.
https://www.waveshare.com/product/modules/oleds-lcds/e-paper/7.5inch-e-paper-hat-c.htm

**Comment by Will711990** [comment]
Hi Andrei !!
Thank you for this very cool project !! 
Could you tell us if your code works with this display (or if somebody does it) : https://www.waveshare.com/product/modules/oleds-lcds/e-paper/7.5inch-e-paper.htm?___SID=U

Thank you !!!

**Comment by andrei7c4** [comment]
I have started work on supporting this display, but unfortunately it is not done yet. Also, it seems that there's a new 7.4" panel from Pervasive Displays: http://www.pervasivedisplays.com/products/740i

**Comment by Will711990** [comment]
Hi !
Thank you for your answer !!
Display from Pervasive is not available...
Are there lot of differences between the 2 models of display ?

**Comment by zpgitlab** [comment]
Hi!
Awesome project. Can I build your project today? I would like to try it, can you send me links for the available parts?
P.Z.

**Comment by not4unco** [comment]
Looking forward to the waveshare code..

**Comment by andrei7c4** [comment]
I have finally added support for Waveshare display. I am personally using this kit and not the "raw display" mentioned earlier: https://www.waveshare.com/7.5inch-e-paper-hat.htm

Binaries are now available in releases.
