### ISSUE TITLE
Weather Display with additional functions

### ISSUE THREAD

**Issue by hogin86** [andrei7c4/weatherdisplay#6]
Hello Andrei,

I would like to expand your Weather Display. For that I would need your help, mainly for the software. I have designed a board with the components from your git description. In addition, I added a 868 Mhz transceiver. I would like to connect the transceiver with a complete radio transmitter. I found something ready on the internet https://nathan.chantrell.net/tinytx-wireless-sensor/   I would like to fade in the radio sensors as an outside temperature sensor. 

If you are interested I would send you more details by e-mail as well as a few pictures of my setup so far. Furthermore, I would like to expand the board so that the new version of the e-paper display works. http://www.pervasivedisplays.com/products/740i

I would also send you a board with wireless sensor so you can customize the software... Is better for you and for me :-)

I look forward to hearing from you!

best regards

Martin

**Comment by andrei7c4** [comment]
Sorry, but I don't really have time for this kind of big project. Good luck with it, though.
